version: "3"
services:
  flask:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5001 app:app --reload
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5001:5001"
    volumes:
    - ./:/root